name: "Test with Ansible 2.12"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@v3
      - run: nix-shell -p ansible_2_12 --command 'ansible-playbook --version'
