name: Test installing role afresh with Ubuntu Ansible Versions
on: [push]
jobs:
  Install-Nix-on-ubuntu-22-04-with-ansible-2-10:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install ansible
      - run: ansible-playbook test/install-role.yml
      - run: . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix-shell -p nix-info --command nix-info
  Install-Nix-on-ubuntu-20-04-with-ansible-2-9:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install ansible
      - run: ansible-playbook test/install-role.yml
      - run: . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix-shell -p nix-info --command nix-info
  Install-Nix-on-ubuntu-18-04-with-ansible-2-5:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install ansible
      - run: ansible-playbook test/install-role.yml
      - run: . /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh && nix-shell -p nix-info --command nix-info
